Cadastro de usuario
DiegoRomario/nosso-calendario pull request #1
Opened 2020-04-28 14:35 UTC by DiegoRomario

- Definição do Setup da aplicação (mapeamento do EF, versionamento, documentação etc)
- Definição de objetos base que serão utilizados em outras features
- Validação de login de usuário com JWT Token
- Cadastro de usuário

2020-04-28 21:40 UTC, asouza requested changes
Oi Diego, para o review ser melhor, eu preciso que remova todo código não necessário para fazer estritamente a criação de um usuário de acordo com a especificação do caso de uso, tudo bem?

2020-04-29 12:19 UTC, DiegoRomario commented
Código desnecessário para o momento removido através do commit f888196. Poderia verificar, por favor?

2020-04-29 16:25 UTC, asouza requested changes
Vamos revisar por partes o código, tudo bem? Ainda existem mais pontos aqui de revisão.

2020-04-29 16:25 UTC, asouza commented on src/NossoCalendario.Webapi/Controllers/V1/UsuarioController.cs
>      public class UsuarioController : ControllerBase
*Toda indireção aumenta a dificuldade de entendimento da aplicação como um todo, ela precisa merecer existir. Ou seja, precisa ajudar a distribuir a carga intrínseca pelo sistema.*

Herança é uma forma de indireção. No caso, a ControllerBase é uma classe padrão do framework e até seria ok herdar dela, já que deveria ser de conhecimento de todos. Minha pergunta básica é: essa classe poderia existir sem essa herança?

2020-04-29 16:25 UTC, asouza commented on src/NossoCalendario.Webapi/Controllers/V1/UsuarioController.cs
>              _mediator = mediator;
*Toda indireção aumenta a dificuldade de entendimento da aplicação como um todo, ela precisa merecer existir. Ou seja, precisa ajudar a distribuir a carga intrínseca pelo sistema.* 
+
*A complicação do nosso é código é proporcional a complicação da nossa feature. Quanto mais simples, melhor.*

Por que temos uma indireção extra no projeto e pelo que entendi provida por uma biblioteca extra? Digo, se a ideia é usar coisas como cqrs, eu preciso de um motivo lógico para isso ser mais fácil de entender do que usar um DbContext direto aqui.

2020-04-29 16:25 UTC, asouza commented on src/NossoCalendario.Webapi/Controllers/V1/UsuarioController.cs
>          public async Task<ActionResult> CadastrarUsuario([FromBody] CadastrarUsuarioCommand usuario)
*Avaliamos de forma lógica o nível de complicação de cada trecho de código. Aqui não tem espaço para feeling. Usamos a teoria da carga cognitiva e medimos o nível de pontos de entendimentos necessário por trecho*

Pq usar isso é mais fácil do que criar um objeto simples representando o formulário? Por exemplo uma ViewModel e adicionar os attributes de validação? A validação já seria aplicada automaticamente pelo framework.

2020-04-29 16:25 UTC, asouza commented on src/NossoCalendario.Webapi/Controllers/V1/UsuarioController.cs
>          public async Task<ActionResult> CadastrarUsuario([FromBody] CadastrarUsuarioCommand usuario)
*Protegemos as bordas do sistema como se não houvesse amanhã.*
+
*Quanto mais externa a borda, mais proteção temos.*

Um ponto de código da aplicação não passa para frente objetos que você sabe que pode estar num estado inválido. E é exatamente isso que acontece no seu código... 

Eu preciso confessar para você que estou para ver um argumento minimamente decente para suportar o uso de um cqrs na maioria dos cenários. Aumenta a carga intrinseca através de mais indireção e não necessariamente me retorna alguma coisa útil.

2020-04-29 16:30 UTC, asouza commented on src/NossoCalendario.Webapi/Controllers/V1/UsuarioController.cs
>      public class UsuarioController : ControllerBase
Tudo bem aqui, eu percebi que não dá mesmo :). Você herda de controller ou controllerbase né? O framework te obriga a isso. Faz sentido? se sim, ok :).

2020-04-29 17:11 UTC, DiegoRomario commented on src/NossoCalendario.Webapi/Controllers/V1/UsuarioController.cs
>      public class UsuarioController : ControllerBase
Sim, faz parte do "template" padrão das controllers.

2020-04-29 17:23 UTC, DiegoRomario commented on src/NossoCalendario.Webapi/Controllers/V1/UsuarioController.cs
>          public async Task<ActionResult> CadastrarUsuario([FromBody] CadastrarUsuarioCommand usuario)
Já existe um objeto específico para validação de sucesso ou erro, no caso a classe 'Response', usada como exemplo para um retorno de sucesso do usuário cadastrado. 
A ideia seria evoluir essa classe conforme o desenviolamento do projeto e manter uma extensão da Controller base onde seria possível adicionar mensagens de validação para um retorno padronizado (algo como o status e a lista de mensagens de validação), porem, como existe apenas uma Controller a implementação não foi realizada para não gerar código a mais neste primeiro momento.

2020-04-29 17:33 UTC, DiegoRomario commented on src/NossoCalendario.Webapi/Controllers/V1/UsuarioController.cs
>              _mediator = mediator;
Neste caso utilizei uma biblioteca externa principalmente para utilizar o recurso do Pipeline Behavior, que me permite executar um código (no caso de validação) antes da chamada de cada ação. Também para centralizar o manipulador de ações em uma camada específica e assim manter as Controllers mais limpas, neste caso a Controller apenas receberia a intenção e o Mediator redirecionaria para o método responsável pela manipulação de dados.

2020-04-29 19:30 UTC, asouza commented on src/NossoCalendario.Webapi/Controllers/V1/UsuarioController.cs
>          public async Task<ActionResult> CadastrarUsuario([FromBody] CadastrarUsuarioCommand usuario)
Se você cria um objeto no estilo ViewModel e coloca as marcacoes de validacao, o asp.net core já não valida e retorna 400 automaticamente? É só isso que precisa.

2020-04-29 19:31 UTC, asouza commented on src/NossoCalendario.Webapi/Controllers/V1/UsuarioController.cs
>              _mediator = mediator;
O que é controller mais limpa? Qual o motivo lógica de ter um controller limpo se a contrapartida é um código cheio de indireção e que aumenta a dificuldade de entendimento?

2020-04-30 13:14 UTC, DiegoRomario commented on src/NossoCalendario.Webapi/Controllers/V1/UsuarioController.cs
>              _mediator = mediator;
Realmente. Obrigado pelas dicas.

2020-04-30 13:15 UTC, DiegoRomario commented on src/NossoCalendario.Webapi/Controllers/V1/UsuarioController.cs
>          public async Task<ActionResult> CadastrarUsuario([FromBody] CadastrarUsuarioCommand usuario)
Refatorado através do commit 5453d12. 
Poderia verificar, por favor?

2020-04-30 17:43 UTC, asouza requested changes

2020-04-30 17:43 UTC, asouza commented on src/NossoCalendario.Webapi/Controllers/V1/UsuarioController.cs
> +            return Ok(value: ResponseBase.Response(usuario));
Opa, aqui a resposta pode ser vazia por enquanto. Não precisamos de ResponseBase :).

2020-04-30 17:43 UTC, asouza commented on src/NossoCalendario.Webapi/Controllers/V1/UsuarioController.cs
> +            await _usuarioRepository.UnitOfWork.Commit();
*Só alteramos estado de referências que criamos. Não mexemos nos objetos alheios. A não ser que esse objeto seja criado para isso, como é o caso de argumentos de métodos de borda mais externa. Estes são, geralmente, associados a frameworks.*

Você recebe um usuarioRepository que não foi você que criou e altera o estado interno dele. E se o ponto de criação da instância da implementação do UsuarioRepository também der um commit? Onde foi que teve o BeginTransaction?  Essa linha não pode estar aqui :).  Eu confesso que não imagino que essa linha precise estar em nenhum lugar. Minha aposta, grande, é que o orm escolhido já deve ter abstração para isso, quando necessário. Por default ele deve até já comitar a ação de inserir o usuário em si.

2020-04-30 17:43 UTC, asouza commented on src/NossoCalendario.Data/Repository/UsuarioRepository.cs
>              usuario.CriptografarSenha(PasswordEncryptorHelper.Hash(usuario.Senha));
*Só alteramos estado de referências que criamos. Não mexemos nos objetos alheios. A não ser que esse objeto seja criado para isso, como é o caso de argumentos de métodos de borda mais externa. Estes são, geralmente, associados a frameworks.*

E se quem invocou o método já encodou a senha do usuário? Você vai encodar de novo. Só alteramos o estado de um parâmetro se ele estiver dentro da regra citada no pilar. Isso dificulta tracking do estado do sistema, faz com que métodos sejam invocados duas vezes no mesmo fluxo e até geram códigos de defesa do sistema que não seriam necessários existir.

2020-04-30 18:37 UTC, DiegoRomario commented on src/NossoCalendario.Webapi/Controllers/V1/UsuarioController.cs
> +            return Ok(value: ResponseBase.Response(usuario));
Corrigido.

2020-04-30 18:44 UTC, DiegoRomario commented on src/NossoCalendario.Webapi/Controllers/V1/UsuarioController.cs
> +            await _usuarioRepository.UnitOfWork.Commit();
Neste caso o 'Commit' contém o método padrão para salvar os dados do ORM, porem, criei um 'wrapper' para que o comportamento de salvar o horário de inclusão e alteração (se houver) seja um comportamento padrão.

2020-04-30 18:54 UTC, DiegoRomario commented on src/NossoCalendario.Data/Repository/UsuarioRepository.cs
>              usuario.CriptografarSenha(PasswordEncryptorHelper.Hash(usuario.Senha));
Perfeita explicação, consegui compreender.
Alterações realizadas.

2020-05-03 09:16 UTC, asouza requested changes

2020-05-03 09:16 UTC, asouza commented on src/NossoCalendario.Webapi/Entensions/StringExtensions.cs
> +    public static class StringExtensions
*A complicação do nosso é código é proporcional a complicação da nossa feature. Quanto mais simples, melhor.*
Toda String precisa ter a habilidade de ser encodada? Aqui é só uma reflexão. Os extensions methods são legais mas, em geral, para código de negócio em si, tendem a ser exageros. Eles são mais aplicáveis para códigos de libs e frameworks, já que eles sim tendem a ser usados em diversas partes da aplicação. 

É importante que toda generalização deixa o código mais complicado. A graaaaaaande maioria do código dentro de uma aplicação de negócio é específico e não genérico.

2020-05-03 09:16 UTC, asouza commented on src/NossoCalendario.Data/Repository/BaseRepository.cs
> +        public async Task Insert(TEntity usuario)
*Toda indireção aumenta a dificuldade de entendimento da aplicação como um todo, ela precisa merecer existir. Ou seja, precisa ajudar a distribuir a carga intrínseca pelo sistema.*

Aqui a indireção não distribui a carga cognitiva do sistema, aumenta simplesmente. O seu código é específico e seu repositório base não faz mais do que o dbSet. Sugiro remover toda essa camada... Se quiser usar o repositório, é só implementar direto o do usuário.

2020-05-04 12:34 UTC, DiegoRomario commented on src/NossoCalendario.Webapi/Entensions/StringExtensions.cs
> +    public static class StringExtensions
Está certo. 
Código alterado no commit ca5d544.

2020-05-04 12:34 UTC, DiegoRomario commented on src/NossoCalendario.Data/Repository/BaseRepository.cs
> +        public async Task Insert(TEntity usuario)
Código refatorado de modo que fiquei mais objetivo e claro. Commit e7a6358

2020-05-04 12:46 UTC, asouza requested changes

2020-05-04 12:46 UTC, asouza commented on src/NossoCalendario.Data/Context/NossoCalendarioContext.cs
> +    public class NossoCalendarioContext : DbContext
Pq a gente precisa do NossoCalendarioContext? Não podíamos usar o DbContext direto?

2020-05-04 12:46 UTC, asouza commented on src/NossoCalendario.Data/Repository/UsuarioRepository.cs
> +            _context?.Dispose();
*Só alteramos estado de referências que criamos. Não mexemos nos objetos alheios. A não ser que esse objeto seja criado para isso, como é o caso de argumentos de métodos de borda mais externa. Estes são, geralmente, associados a frameworks.*

Este código altera o estado do context, sendo que não foi ele que criou. E se alguém chamar o Dispose em outro lugar?

2020-05-04 20:11 UTC, DiegoRomario commented on src/NossoCalendario.Data/Context/NossoCalendarioContext.cs
> +    public class NossoCalendarioContext : DbContext
O principal motivo é para mapear os Dbset's. Não funcionaria sem o mapeamento.
Também é necessário para pegar o mapeamento (Fluent Api) das classes de forma dinâmica, através do metodo ApplyConfigurationsFromAssembly. (itens da pasta Mapping)

E implementei o HandleFieldType para que eu possa mapear os campos com os tipos que eu quiser no SQL. Por padrão o campo DateTime é gerado como DateTime2 no banco e acredito que o DateTime seja mais apropriado.

2020-05-04 20:16 UTC, DiegoRomario commented on src/NossoCalendario.Data/Repository/UsuarioRepository.cs
> +            _context?.Dispose();
Corrigido no 097074c.

2020-05-05 08:47 UTC, asouza commented on src/NossoCalendario.Data/Context/NossoCalendarioContext.cs
> +    public class NossoCalendarioContext : DbContext
Entendo. Sobre o tipo da coluna do banco de dados, pq você entende dessa forma?

2020-05-05 08:47 UTC, asouza approved these changes

2020-05-05 12:25 UTC, DiegoRomario commented on src/NossoCalendario.Data/Context/NossoCalendarioContext.cs
> +    public class NossoCalendarioContext : DbContext
Especificamente sobre o Datetime2 o mesmo suporta data mínima desde o ano 0001 e acredito que não seja viável para nossa aplicação.

2020-05-05 12:25 UTC, merged